//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop.
        /// </summary>
        internal static string Bishop {
            get {
                return ResourceManager.GetString("Bishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black_bishop.
        /// </summary>
        internal static string BlackBishop {
            get {
                return ResourceManager.GetString("BlackBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black_king.
        /// </summary>
        internal static string BlackKing {
            get {
                return ResourceManager.GetString("BlackKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black_knight.
        /// </summary>
        internal static string BlackKnight {
            get {
                return ResourceManager.GetString("BlackKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black_pawn.
        /// </summary>
        internal static string BlackPawn {
            get {
                return ResourceManager.GetString("BlackPawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black_queen.
        /// </summary>
        internal static string BlackQueen {
            get {
                return ResourceManager.GetString("BlackQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black_rook.
        /// </summary>
        internal static string BlackRook {
            get {
                return ResourceManager.GetString("BlackRook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_piece.
        /// </summary>
        internal static string NoPiece {
            get {
                return ResourceManager.GetString("NoPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn.
        /// </summary>
        internal static string Pawn {
            get {
                return ResourceManager.GetString("Pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook.
        /// </summary>
        internal static string Rook {
            get {
                return ResourceManager.GetString("Rook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_bishop.
        /// </summary>
        internal static string WhiteBishop {
            get {
                return ResourceManager.GetString("WhiteBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_king.
        /// </summary>
        internal static string WhiteKing {
            get {
                return ResourceManager.GetString("WhiteKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_knight.
        /// </summary>
        internal static string WhiteKnight {
            get {
                return ResourceManager.GetString("WhiteKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_pawn.
        /// </summary>
        internal static string WhitePawn {
            get {
                return ResourceManager.GetString("WhitePawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_queen.
        /// </summary>
        internal static string WhiteQueen {
            get {
                return ResourceManager.GetString("WhiteQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_rook.
        /// </summary>
        internal static string WhiteRook {
            get {
                return ResourceManager.GetString("WhiteRook", resourceCulture);
            }
        }
    }
}
